# CLI tools
brew "gh"
brew "go"
brew "mosh"
brew "node"
brew "nvm"
brew "socat"
brew "btop"
brew "carapace"
brew "starship"
brew "tmux"

# GUI apps (skip with: brew bundle --file=Brewfile --no-cask)
cask "fastmail"
cask "ghostty"
cask "linear-linear"
cask "istat-menus"
cask "orbstack"
cask "raycast"
cask "font-jetbrains-mono"
cask "zed"
